version: '3.8'
services:
  frontend:
    image: nextjs:latest
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
  backend:
    image: node:18
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: "npm start"
